# You'll need to setup the follwing environment variables:
#   env.repo_nightly - The repository to release nightly builds to e.g. betaflight-nightly
#   env.release_notes - The release notes to be published as part of the github release
#   env.debug_release_notes - The release notes to be published as part of the github debug release
#   secrets.REPO_TOKEN - A GitHub token with permissions to push and publish releases to the nightly repo

env:
  repo_nightly: betaflight/betaflight-nightlies
  debug_release_notes: >
    This is an automated development build.
    It may be unstable and result in craft loss or damage.
    **Use only for testing.**
  release_notes: This is a release build. 

name: Nightly

on:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches:
      - master

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    with:
      release_build: false